// 第24届台湾金曲奖（2013年）获奖名单。资料来源：文化部影视及流行音乐产业局官方开放数据。
import type { GmaEditionData } from "./types";

const edition24: GmaEditionData = {
  edition: 24,
  year: 2013,
  categories: [
    { name: "最佳年度歌曲奖", winner: "蔡依林", title: "大艺术家（MUSE）" },
    { name: "最佳国语专辑奖", winner: "林忆莲", title: "盖亚" },
    { name: "最佳台语专辑奖", winner: "谢铭祐", title: "台南" },
    { name: "最佳客语专辑奖", winner: "暗黑白领阶级", title: "回家的路" },
    { name: "最佳原住民语专辑奖", winner: "欧开合唱团", title: "O-Kai A Cappella" },
    { name: "最佳音乐录影带奖", winner: "陈奕仁", title: "干杯（第二人生 no where 末日版）" },
    { name: "最佳作曲人奖（流行音乐类）", winner: "黄韵玲", title: "回味（永恒．承诺）" },
    { name: "最佳作词人奖（流行音乐类）", winner: "焦安溥", title: "玫瑰色的你（神的游戏）" },
    { name: "最佳编曲人奖", winner: "常石磊", title: "盖亚（盖亚）" },
    { name: "最佳专辑制作人奖（流行音乐类）", winner: "林忆莲、常石磊", title: "盖亚" },
    { name: "最佳单曲制作人奖", winner: "乱弹阿翔", title: "不一样的朋友（忘不记）" },
    { name: "最佳国语男歌手奖", winner: "萧敬腾", title: "以爱之名" },
    { name: "最佳台语男歌手奖", winner: "谢铭祐", title: "台南" },
    { name: "最佳国语女歌手奖", winner: "林忆莲", title: "盖亚" },
    { name: "最佳台语女歌手奖", winner: "李娅莎", title: "爱" },
    { name: "最佳客语歌手奖", winner: "汤宇歆", title: "两个世界" },
    { name: "最佳原住民语歌手奖", winner: "卢皆兴（桑布伊）", title: "桑布伊同名专辑─dalan" },
    { name: "最佳乐团奖", winner: "猴子飞行员 Monkey Pilot（王汤尼、杨声铮、陈自强、余光燿、王昱人）", title: "Big Child" },
    { name: "最佳演唱组合奖", winner: "欧开合唱团（赖家庆、叶微真、叶孝恩、叶孝贤、薛诒丹、李志伟）", title: "O-Kai A Cappella" },
    { name: "最佳新人奖", winner: "葛仲珊（MISS KO）", title: "Knock Out 葛屁" },
    { name: "最佳专辑奖（演奏类）", winner: "果核有限公司", title: "钟兴民作品集─饮食男女II 原声带" },
    { name: "最佳专辑制作人奖（演奏类）", winner: "Daniel Ho", title: "吹过岛屿的风" },
    { name: "最佳作曲人奖（演奏类）", winner: "陈欣若", title: "颐和园华尔兹（爱 无界）" },
    { name: "最佳专辑包装奖（流行音乐类）", winner: "萧青阳", title: "卡片教堂的钟声" },
    { name: "评审团奖（流行音乐类）", winner: "欧开合唱团", title: "O-Kai A Cappella" },
    { name: "特别贡献奖（流行音乐类）", winner: "凤飞飞（林秋鸾）" },
    { name: "最佳民族音乐专辑奖", winner: "风潮音乐国际股份有限公司", title: "无极－春夏秋冬" },
    { name: "最佳戏曲曲艺专辑奖", winner: "长德有线电视股份有限公司", title: "新编昆剧《梁山伯与祝英台》" },
    { name: "最佳传统歌乐专辑奖", winner: "财团法人明基友达文教基金会", title: "霞喀罗精灵的秘密语" },
    { name: "最佳古典音乐专辑奖", winner: "缪斯艺术文化有限公司", title: "台北单簧管乐集 Live Recording" },
    { name: "最佳儿童音乐专辑奖", winner: "源动力文化发展事业有限公司", title: "爱如小孩" },
    { name: "最佳宗教音乐专辑奖", winner: "风潮音乐国际股份有限公司", title: "油菜花开的季节" },
    { name: "最佳跨界音乐专辑奖", winner: "陈明章音乐工作有限公司", title: "花漾" },
    { name: "最佳作曲人奖（传统暨艺术音乐类）", winner: "钟耀光", title: "Works for Percussion and Chinese Orchestra（击境）" },
    { name: "最佳作词人奖（传统暨艺术音乐类）", winner: "曾永义", title: "梁山伯与祝英台（新编昆剧《梁山伯与祝英台》）" },
    { name: "最佳编曲人奖（传统暨艺术音乐类）", winner: "詹勋伟", title: "嬉春 / 惊蛰（无极－春夏秋冬）" },
    { name: "最佳专辑制作人奖（传统暨艺术音乐类）", winner: "叶绿娜、尤子泽", title: "在野的红蔷薇─郭芝苑钢琴独奏曲集" },
    { name: "最佳传统音乐诠释奖", winner: "吴钊", title: "山居吟─吴钊经典古琴演奏" },
    { name: "最佳演唱奖（传统暨艺术音乐类）", winner: "SURE 人声乐团", title: "南岛 Vali" },
    { name: "最佳演奏奖（传统暨艺术音乐类）", winner: "陆威、周启、陈麒元、赵耀", title: "长城" },
    { name: "最佳专辑包装奖（传统暨艺术音乐类）", winner: "黄慧甄、郑司维", title: "南岛 Vali" },
    { name: "评审团奖（传统暨艺术音乐类）", winner: "彭双松、彭文铭", title: "穿越时空半世纪─传唱马兰古谣" },
  ],
};

export default edition24;
