// 第20届台湾金曲奖（2009年）获奖名单。资料来源：文化部影视及流行音乐产业局官方开放数据，得奖者人名参考百度百科补全。
import type { GmaEditionData } from "./types";

const edition20: GmaEditionData = {
  edition: 20,
  year: 2009,
  categories: [
    { name: "最佳年度歌曲奖", winner: "周杰伦", title: "稻香（魔杰座）" },
    { name: "最佳国语专辑奖", winner: "陈奕迅", title: "不想放手" },
    { name: "最佳台语专辑奖", winner: "江蕙", title: "甲你揽牢牢" },
    { name: "最佳客语专辑奖", winner: "好客乐队", title: "爱吃饭" },
    { name: "最佳原住民语专辑奖", winner: "南王姐妹花", title: "南王姐妹花同名专辑" },
    { name: "最佳音乐录影带奖", winner: "周杰伦", title: "魔术先生（魔杰座）" },
    { name: "最佳作曲人奖（流行音乐类）", winner: "卢广仲", title: "100种生活（100种生活）" },
    { name: "最佳作词人奖（流行音乐类）", winner: "巫宇轩", title: "电车内面（甲你揽牢牢）" },
    { name: "最佳编曲人奖", winner: "Martin Tang", title: "As Love Begins to Mend（Start from Here）" },
    { name: "最佳专辑制作人奖（流行音乐类）", winner: "陈建年", title: "南王姐妹花同名专辑" },
    { name: "最佳单曲制作人奖", winner: "王治平、郭文宗", title: "眼色（神秘嘉宾）" },
    { name: "最佳国语男歌手奖", winner: "周杰伦", title: "魔杰座" },
    { name: "最佳台语男歌手奖", winner: "翁立友", title: "行棋" },
    { name: "最佳国语女歌手奖", winner: "陈珊妮", title: "如果有一件事是重要的" },
    { name: "最佳台语女歌手奖", winner: "黄乙玲", title: "讲乎自己听" },
    { name: "最佳客语歌手奖", winner: "刘劭希", title: "唬客船长" },
    { name: "最佳原住民语歌手奖", winner: "云力思", title: "Gaga" },
    { name: "最佳乐团奖", winner: "五月天（阿信、怪兽、玛莎、冠佑、石头）", title: "后青春期的诗" },
    { name: "最佳演唱组合奖", winner: "南王姐妹花（陈惠琴、李谕芹、徐美花）", title: "南王姐妹花同名专辑" },
    { name: "最佳新人奖", winner: "卢广仲", title: "100种生活" },
    { name: "最佳专辑奖（演奏类）", winner: "吴书齐爵士乐团", title: "倒影" },
    { name: "最佳专辑制作人奖（演奏类）", winner: "吴书齐", title: "倒影" },
    { name: "最佳作曲人奖（演奏类）", winner: "纪华麟", title: "森林的呼唤（寻找精灵－纪华麟）" },
    { name: "评审团奖（流行音乐类）", winner: "参拾柒度制作有限公司", title: "敬！李双泽 唱自己的歌" },
    { name: "特别贡献奖", winner: "段钟潭" },
    { name: "最佳民族音乐专辑奖", winner: "普音文化事业股份有限公司", title: "古苑寻声－王世荣的琵琶新视界" },
    { name: "最佳戏曲曲艺专辑奖", winner: "李静芳戏曲工作室", title: "李静芳个人唱唸专辑" },
    { name: "最佳传统歌乐专辑奖", winner: "吉声影视音有限公司", title: "王凤珠的山歌戏" },
    { name: "最佳古典音乐专辑奖", winner: "十方乐集", title: "声动" },
    { name: "最佳儿童音乐专辑奖", winner: "和英出版社", title: "永远的儿歌－小球听国乐 外婆桥" },
    { name: "最佳宗教音乐专辑奖", winner: "如是我闻文化股份有限公司", title: "慈悲三昧水忏" },
    { name: "最佳跨界音乐专辑奖", winner: "豆菜芽子音乐工作室", title: "王明华爵士二胡登峰造极" },
    { name: "最佳作曲人奖（传统暨艺术音乐类）", winner: "卢炎", title: "十方协奏曲 给双钢琴与打击乐团（声动）" },
    { name: "最佳作词人奖（传统暨艺术音乐类）", winner: "李子恒", title: "成长（礼赞）" },
    { name: "最佳编曲人奖（传统暨艺术音乐类）", winner: "董舜文", title: "Sometime in My Life 流光掠影（欢．日．纪 One Day）" },
    { name: "最佳专辑制作人奖（传统暨艺术音乐类）", winner: "王森地、吴金黛", title: "蒙古长调民歌" },
    { name: "最佳传统音乐诠释奖", winner: "温宇航", title: "兰庭六记" },
    { name: "最佳演唱奖（传统暨艺术音乐类）", winner: "李文智", title: "圣母哀悼曲" },
    { name: "最佳演奏奖（传统暨艺术音乐类）", winner: "任洁", title: "枫桥夜泊－任洁的古筝怀想" },
    { name: "评审团奖（传统暨艺术音乐类）", winner: "东埔国小合唱团", title: "唱歌吧！" },
    { name: "特别贡献奖（传统暨艺术音乐类）", winner: "吴兆南" },
  ],
};

export default edition20;
