// 第22届台湾金曲奖（2011年）获奖名单。资料来源：文化部影视及流行音乐产业局官方开放数据，得奖者人名参考百度百科补全。
import type { GmaEditionData } from "./types";

const edition22: GmaEditionData = {
  edition: 22,
  year: 2011,
  categories: [
    { name: "最佳年度歌曲奖", winner: "纵贯线（李宗盛）", title: "给自己的歌（南[下]专线）" },
    { name: "最佳国语专辑奖", winner: "周杰伦", title: "跨时代" },
    { name: "最佳台语专辑奖", winner: "江蕙", title: "当时欲嫁" },
    { name: "最佳客语专辑奖", winner: "栾克勇", title: "独1无2 反串客" },
    { name: "最佳原住民语专辑奖", winner: "舒米恩", title: "Suming 舒米恩首张个人创作专辑" },
    { name: "最佳音乐录影带奖", winner: "徐筠轩", title: "寂寞寂寞就好（To Hebe）" },
    { name: "最佳作曲人奖（流行音乐类）", winner: "李宗盛（纵贯线）", title: "给自己的歌（南[下]专线）" },
    { name: "最佳作词人奖（流行音乐类）", winner: "李宗盛（纵贯线）", title: "给自己的歌（南[下]专线）" },
    { name: "最佳编曲人奖", winner: "蔡科俊 Again", title: "免费教学录影带（跨时代）" },
    { name: "最佳专辑制作人奖（流行音乐类）", winner: "洪敬尧", title: "恋花" },
    { name: "最佳单曲制作人奖", winner: "王治平", title: "LOVE！（To Hebe）" },
    { name: "最佳国语男歌手奖", winner: "周杰伦", title: "跨时代" },
    { name: "最佳台语男歌手奖", winner: "黄文星", title: "天地" },
    { name: "最佳国语女歌手奖", winner: "莫文蔚", title: "宝贝" },
    { name: "最佳台语女歌手奖", winner: "黄妃", title: "黄妃 相思声声" },
    { name: "最佳客语歌手奖", winner: "栾克勇", title: "独1无2 反串客" },
    { name: "最佳原住民语歌手奖", winner: "林广财", title: "百年排湾 风华再现 排湾族头目林广财专辑" },
    { name: "最佳乐团奖", winner: "MATZKA（Matzka、Sakinu 阿辉、Mavaliw 阿胜、Nanwan 阿修）", title: "MATZKA" },
    { name: "最佳演唱组合奖", winner: "大嘴巴（爱纱、怀秋、MC40、DJ宗华）", title: "万凸3" },
    { name: "最佳新人奖", winner: "韦礼安", title: "韦礼安首张同名全创作专辑" },
    { name: "最佳专辑奖（演奏类）", winner: "威幅音乐有限公司", title: "无限融合党 Timeless Fusion Party" },
    { name: "最佳专辑制作人奖（演奏类）", winner: "雷光夏、侯志坚", title: "第36个故事电影原声音乐大碟 她的改变" },
    { name: "最佳作曲人奖（演奏类）", winner: "侯志坚", title: "这就是城市（第36个故事电影原声音乐大碟 她的改变）" },
    { name: "最佳专辑包装奖（流行音乐类）", winner: "刘悦德", title: "Kiss Your Eyes" },
    { name: "特别贡献奖（流行音乐类）", winner: "黄敏（黄东焜）" },
    { name: "最佳民族音乐专辑奖", winner: "缪斯艺术文化有限公司", title: "台湾四季" },
    { name: "最佳传统歌乐专辑奖", winner: "风潮音乐国际股份有限公司", title: "寻回失落的印记" },
    { name: "最佳古典音乐专辑奖", winner: "雅砌音乐有限公司", title: "你知道的．陈威棱与单簧管的6个漫游" },
    { name: "最佳儿童音乐专辑奖", winner: "吉声影视音有限公司", title: "月光华华" },
    { name: "最佳宗教音乐专辑奖", winner: "福尔摩沙合唱团", title: "至好朋友就是耶稣" },
    { name: "最佳跨界音乐专辑奖", winner: "世界轨迹乐团", title: "失落的环节 The Missing Link" },
    { name: "最佳作曲人奖（传统暨艺术音乐类）", winner: "张琼樱", title: "射日（前进的节奏）" },
    { name: "最佳作词人奖（传统暨艺术音乐类）", winner: "林夕", title: "春秋配（我一直听见自己的笙音）" },
    { name: "最佳编曲人奖（传统暨艺术音乐类）", winner: "陈彤", title: "塔玲珑（我一直听见自己的笙音）" },
    { name: "最佳专辑制作人奖（传统暨艺术音乐类）", winner: "吴马丁 Martijn Vanbuel", title: "失落的环节 The Missing Link" },
    { name: "最佳传统音乐诠释奖", winner: "布农山地传统音乐团", title: "雾来了！世界的声脉" },
    { name: "最佳演唱奖（传统暨艺术音乐类）", winner: "周文彬、游宜群", title: "春风" },
    { name: "最佳演奏奖（传统暨艺术音乐类）", winner: "陈毓襄", title: "陈毓襄 珍爱的萧邦" },
    { name: "最佳专辑包装奖（传统暨艺术音乐类）", winner: "高鹏翔", title: "心花儿开满年" },
    { name: "评审团奖（传统暨艺术音乐类）", winner: "赖碧霞", title: "送客传家宝" },
    { name: "特别贡献奖（传统暨艺术音乐类）", winner: "萧泰然" },
  ],
};

export default edition22;
