// 第21届台湾金曲奖（2010年）获奖名单。资料来源：文化部影视及流行音乐产业局官方开放数据，得奖者人名参考百度百科补全。
import type { GmaEditionData } from "./types";

const edition21: GmaEditionData = {
  edition: 21,
  year: 2010,
  categories: [
    { name: "最佳年度歌曲奖", winner: "张惠妹（阿密特）", title: "好胆你就来（A-MIT 阿密特 张惠妹意识专辑）" },
    { name: "最佳国语专辑奖", winner: "张惠妹（阿密特）", title: "A-MIT 阿密特 张惠妹意识专辑" },
    { name: "最佳台语专辑奖", winner: "大吉祥整合行销有限公司", title: "大员一家农出来" },
    { name: "最佳客语专辑奖", winner: "曾雅君", title: "Yachun Asta Tzeng 曾雅君" },
    { name: "最佳原住民语专辑奖", winner: "参拾柒度制作有限公司", title: "八部传说 布农" },
    { name: "最佳音乐录影带奖", winner: "林暐哲、陈映之", title: "日光（春．日光）" },
    { name: "最佳作曲人奖（流行音乐类）", winner: "陈小霞", title: "在树上唱歌（在树上唱歌）" },
    { name: "最佳作词人奖（流行音乐类）", winner: "林夕", title: "开门见山（A-MIT 阿密特 张惠妹意识专辑）" },
    { name: "最佳编曲人奖", winner: "Martin Teng", title: "好胆你就来（A-MIT 阿密特 张惠妹意识专辑）" },
    { name: "最佳专辑制作人奖（流行音乐类）", winner: "阿弟仔", title: "A-MIT 阿密特 张惠妹意识专辑" },
    { name: "最佳单曲制作人奖", winner: "范晓萱", title: "主人（赤子 Innocent）" },
    { name: "最佳国语男歌手奖", winner: "陶喆", title: "69乐章 Zero to Hero" },
    { name: "最佳台语男歌手奖", winner: "萧煌奇", title: "爱作梦的人" },
    { name: "最佳国语女歌手奖", winner: "张惠妹（阿密特）", title: "A-MIT 阿密特 张惠妹意识专辑" },
    { name: "最佳台语女歌手奖", winner: "曾心梅", title: "牵线" },
    { name: "最佳客语歌手奖", winner: "官灵芝", title: "头摆的你" },
    { name: "最佳原住民语歌手奖", winner: "查劳．加麓", title: "查劳．巴西瓦里－老老车" },
    { name: "最佳乐团奖", winner: "1976", title: "不合时宜" },
    { name: "最佳演唱组合奖", winner: "大囍门", title: "大囍门 X 专辑" },
    { name: "最佳新人奖", winner: "徐佳莹", title: "LALA 创作专辑" },
    { name: "最佳专辑奖（演奏类）", winner: "丝竹空爵士乐团", title: "纸鸢 Paper Eagle" },
    { name: "最佳专辑制作人奖（演奏类）", winner: "彭郁雯", title: "纸鸢 Paper Eagle" },
    { name: "最佳作曲人奖（演奏类）", winner: "李欣芸", title: "大稻埕（故事岛）" },
    { name: "最佳专辑包装奖", winner: "聂永真", title: "感官 / 世界" },
    { name: "评审团奖（流行音乐类）", winner: "李宗盛、罗大佑、周华健、张震嶽", title: "纵贯线 Super Band 北上列车" },
    { name: "特别贡献奖", winner: "洪一峰" },
    { name: "最佳民族音乐专辑奖", winner: "上扬国际股份有限公司", title: "胡旋舞" },
    { name: "最佳戏曲曲艺专辑奖", winner: "许亚芬歌子戏剧坊", title: "良臣遇灶神" },
    { name: "最佳传统歌乐专辑奖", winner: "猫狸文化工作室", title: "福佬民谣" },
    { name: "最佳古典音乐专辑奖", winner: "环球国际唱片股份有限公司", title: "双钢琴30礼赞" },
    { name: "最佳儿童音乐专辑奖", winner: "静思人文志业股份有限公司", title: "幸福的脸－儿童音乐专辑" },
    { name: "最佳宗教音乐专辑奖", winner: "如是我闻文化股份有限公司", title: "梁皇宝忏" },
    { name: "最佳跨界音乐专辑奖", winner: "看见音乐股份有限公司", title: "乐活无界 Beyond Boundaries" },
    { name: "最佳作曲人奖（传统暨艺术音乐类）", winner: "萧泰然", title: "家园的回忆（萧泰然钢琴独奏曲集－家园的回忆）" },
    { name: "最佳作词人奖（传统暨艺术音乐类）", winner: "王安祈", title: "青塚前的对话" },
    { name: "最佳编曲人奖（传统暨艺术音乐类）", winner: "梁启慧", title: "赤壁之后（乐活无界 Beyond Boundaries）" },
    { name: "最佳专辑制作人奖（传统暨艺术音乐类）", winner: "程芷香", title: "自由想－源自远古的呼声" },
    { name: "最佳传统音乐诠释奖", winner: "陈美兰", title: "青塚前的对话" },
    { name: "最佳演唱奖（传统暨艺术音乐类）", winner: "台北室内合唱团（指挥：陈云红）", title: "当代狂潮－当代合唱音乐作品集" },
    { name: "最佳演奏奖（传统暨艺术音乐类）", winner: "魏乐富、叶绿娜", title: "双钢琴30礼赞" },
    { name: "最佳专辑包装奖（传统暨艺术音乐类）", winner: "高森信男", title: "摇篮．记忆" },
    { name: "评审团奖（传统暨艺术音乐类）", winner: "上扬国际股份有限公司", title: "胡旋舞" },
  ],
};

export default edition21;
