// 第23届台湾金曲奖（2012年）获奖名单。资料来源：文化部影视及流行音乐产业局官方开放数据，得奖者人名参考百度百科补全。
import type { GmaEditionData } from "./types";

const edition23: GmaEditionData = {
  edition: 23,
  year: 2012,
  categories: [
    { name: "最佳年度歌曲奖", winner: "五月天", title: "诺亚方舟（第二人生 no where 末日版）" },
    { name: "最佳国语专辑奖", winner: "五月天", title: "第二人生（no where 末日版）" },
    { name: "最佳台语专辑奖", winner: "萧煌奇", title: "思念会惊" },
    { name: "最佳客语专辑奖", winner: "罗思容", title: "揽花去" },
    { name: "最佳原住民语专辑奖", winner: "以莉．高露", title: "轻快的生活" },
    { name: "最佳音乐录影带奖", winner: "比尔贾", title: "寂寞疯了（于是长大了以后）" },
    { name: "最佳作曲人奖（流行音乐类）", winner: "五月天玛莎", title: "诺亚方舟（第二人生 no where 末日版）" },
    { name: "最佳作词人奖（流行音乐类）", winner: "武雄", title: "阿爸的虱目鱼（思念会惊）" },
    { name: "最佳编曲人奖", winner: "五月天、陈建骐", title: "诺亚方舟（第二人生 no where 末日版）" },
    { name: "最佳专辑制作人奖（流行音乐类）", winner: "五月天", title: "第二人生（no where 末日版）" },
    { name: "最佳单曲制作人奖", winner: "薛忠铭", title: "那些年（那些年，我们一起追的女孩）" },
    { name: "最佳国语男歌手奖", winner: "乱弹阿翔", title: "把我换成你（十年幕后创作精华 电影电视主题歌曲专辑）" },
    { name: "最佳台语男歌手奖", winner: "荒山亮", title: "天荒地老" },
    { name: "最佳国语女歌手奖", winner: "蔡健雅", title: "说到爱" },
    { name: "最佳台语女歌手奖", winner: "谢金燕", title: "月弯弯" },
    { name: "最佳客语歌手奖", winner: "罗思容", title: "揽花去" },
    { name: "最佳原住民语歌手奖", winner: "以莉．高露", title: "轻快的生活" },
    { name: "最佳乐团奖", winner: "五月天（温尚翊、蔡昇晏、陈信宏、石锦航、刘冠佑）", title: "第二人生（no where 末日版）" },
    { name: "最佳演唱组合奖", winner: "新宝岛康乐队（陈昇、陈世隆）", title: "新宝岛康乐队「八」脚开开" },
    { name: "最佳新人奖", winner: "以莉．高露", title: "轻快的生活" },
    { name: "最佳专辑奖（演奏类）", winner: "果核有限公司", title: "被遗忘的时光" },
    { name: "最佳专辑制作人奖（演奏类）", winner: "何国杰", title: "赛德克．巴莱" },
    { name: "最佳作曲人奖（演奏类）", winner: "钟兴民", title: "谁偷走了时间（被遗忘的时光）" },
    { name: "最佳专辑包装奖（流行音乐类）", winner: "陈政守 Mori Chen（守工异）", title: "惊叹号（限量USB版）" },
    { name: "特别贡献奖（流行音乐类）", winner: "文夏（王瑞河）" },
    { name: "最佳民族音乐专辑奖", winner: "贝冈朵音乐艺术企业社", title: "秀才骑马弄弄来－台湾笛子作品专辑（一）" },
    { name: "最佳古典音乐专辑奖", winner: "雅砌音乐有限公司", title: "看见萧邦 X 胡瀞云：胡瀞云钢琴演奏专辑" },
    { name: "最佳儿童音乐专辑奖", winner: "甄艺乐场", title: "嘻游记－二胡游台湾" },
    { name: "最佳宗教音乐专辑奖", winner: "福尔摩沙合唱团", title: "福尔摩沙合唱团大师系列音乐会之四 宗教歌曲" },
    { name: "最佳跨界音乐专辑奖", winner: "风潮音乐国际股份有限公司", title: "迁徙" },
    { name: "最佳作曲人奖（传统暨艺术音乐类）", winner: "李哲艺", title: "弦舞I（弦舞．台湾）" },
    { name: "最佳作词人奖（传统暨艺术音乐类）", winner: "向阳", title: "秋风读未出阮的相思（台湾音乐剧三部曲《渭水春风》首演原声唱片）" },
    { name: "最佳编曲人奖（传统暨艺术音乐类）", winner: "洪千惠", title: "深情相拥（Ever Blooming 百合盛开－跨界美声交响诗）" },
    { name: "最佳专辑制作人奖（传统暨艺术音乐类）", winner: "饶瑞舜、欧光勋", title: "阅读卢亮辉" },
    { name: "最佳传统音乐诠释奖", winner: "泰武国小古谣传唱", title: "歌开始的地方" },
    { name: "最佳演唱奖（传统暨艺术音乐类）", winner: "拉纤人男声合唱团", title: "当代无伴奏男声合唱－千缕清风 A Thousand Winds" },
    { name: "最佳演奏奖（传统暨艺术音乐类）", winner: "卢易之", title: "My Chopin My Brahms" },
    { name: "最佳专辑包装奖（传统暨艺术音乐类）", winner: "萧青阳", title: "不只唱歌吧" },
    { name: "特别贡献奖（传统暨艺术音乐类）", winner: "史撷咏" },
  ],
};

export default edition23;
